sailfishos/sailfish-browser

src/pages/components/Overlay.qml

Favorite grid and history list are enabled only after overlay
is atTop state (fully opened).

[sailfish-browser] Enable overlay content when it is fully opened

---

src/pages/components/Overlay.qml

Position both favorite grid and history list to the beginning when
overlay reaches bottom.

[sailfish-browser] Position overlay flickables to beginning when overlay is hidden

---

tests/auto/tests.xml
tests/auto/tst_webview/tst_webview.cpp

This also increases timeout to 30sec as default timeout (90sec)
was really close.

[sailfish-browser] Improve WebView unit test execution speed

---

src/pages/components/Overlay.qml

Overlay cannot be opened by dragging meaning that dragging can be only used
to lower the overlay. Thus, we should not disable dragging in fullscreen
mode.
For instance, when playing a video in fullscreen and a new tab requested
from cover it should be possible to close the overlay by dragging it.

[sailfish-browser] Do not limit dragging of overlay in fullscreen mode

---

src/pages/components/FavoriteIcon.qml

In case the server is not responding or favorite icon is not found
from server icon will be replaced by default icon.

[sailfish-browser] Add error handling for favorite icons.

---

src/declarativewebcontainer.cpp
src/declarativewebpage.cpp
src/declarativewebpage.h
src/declarativewebutils.cpp
src/downloadmanager.cpp
src/downloadmanager.h
tests/auto/common/downloadmanager.cpp
tests/auto/common/downloadmanager.h

Subject: [sailfish-browser] Do not add initial url to the tab model
Initial url can be a download url.
Subject: [sailfish-browser] At startup wait that Download Manager is initialized
Do not mark DeclarativeWebContainer as initialized before mozilla context,
download manager, web container itself, and tab model are completed/initialized.

Fix initial download url

---

src/pages/components/FavoriteGrid.qml
src/pages/components/Overlay.qml

If ContextMenu is active when FavoriteGrid changes invisible
ContextMenu is explicitly hidden / closed.

[sailfish-browser] Fix favorite grid context menu issues

---

rpm/sailfish-browser.spec

jobs is non-standard and won't use multiple cores when building under mb2, unlike _smp_mflags.

Build with multiple cores when using mb2.

---

src/declarativewebcontainer.cpp

The disconnect method with a single argument doesn't actually disconnect signals even though it compiles

[webcontainer] Actually disconnect signals from TabModel

---

rpm/sailfish-browser.spec
src/pages/BrowserPage.qml

Rebased: https://github.com/sailfishos/sailfish-browser/pull/290

[sailfish-browser] Limit active cover actions to one for Sailfish 2.0

---

src/pages/components/TabView.qml

On large screen
- 2 columns on portrait
- 3 columns on landscape

[sailfish-browser] Use grid layout for tab view on large screen

---

src/dbmanager.cpp
src/dbmanager.h
src/dbworker.cpp
src/dbworker.h
src/declarativetabmodel.cpp
src/declarativetabmodel.h
src/declarativewebcontainer.cpp
src/declarativewebcontainer.h
src/persistenttabmodel.cpp
tests/auto/tst_webview/tst_webview.cpp

The slot DeclarativeWebContainer::onTabsCleared() is redundant as
for every deleted webview DeclarativeWebContainer::releasePage() is
called and in this method we can do the same resets upon emptying
the current tabs model (DeclarativeWebContainer::m_model).
Since DeclarativeWebContainer::onTabsCleared() is the only client
for DeclarativeTabModel::tabsCleared() signal the signal has been
removed as well.
Also DBManager::removeAllTabs() has been removed as unused.

[sailfish-browser] Remove redundant tabsCleared signal JB#26644

---

src/declarativewebcontainer.cpp
src/declarativewebcontainer.h

While we are in process of activating a tab, do not pass title and url
of the active page through as it is already out dated. Previously this
caused an issue when cached url / title (m_url / m_title) got updated
and matching change signals were emitted right after new tab data became
available. When QML side tried to read updated value we returned
the value of the previous page.
As all title and url updates are done through updateTitle and updateUrl, when setWebPage
got called m_title and m_url were already up-to-date. Thus, change signals
didn't get emitted again.

[sailfish-browser] While activating a tab do not use page's title and url

---

src/dbworker.cpp

[sailfish-browser] Limit history size to 2000 entries

---

src/pages/components/BrowserContextMenu.qml

For some reason QML thinks that a property declaration is the same as class instantiation. And since TabModel is an abstract class QML fails to load BrowserContextMenu.qml.

[sailfish-browser] Don't instantiate an abstract class. JB#27654

---

src/sailfishbrowser.cpp

Intermediate step so that MOZ_LAYERS_PREFER_OFFSCREEN can be removed
from embedlite with breaking things.

[sailfish-browser] Move MOZ_LAYERS_PREFER_OFFSCREEN to browser side. Contributes to JB#27561

---

src/pages/components/Overlay.qml

Closing the favorite grid overlay from the space between right edge of screen and right-most icon is not allowing dragging gesture, similar at the left edge.

[sailfish-browser] Fix favorite grid overlay edges for bigger screens.

---

common/common.pri
common/opensearchconfigs.cpp
common/opensearchconfigs.h
settings/browsersettings.cpp
settings/settings.pro
src/declarativewebutils.cpp
src/src.pro

Fixes #254
Read opensearch descriptors from '/home/nemo/.local/share/org.sailfishos/sailfish-browser/searchEngines/'

[sailfish-browser] Allow adding new search engines

---

src/pages/components/TabItem.qml

I still don't understand how exactly, but this patch seems to fix the crashes when creating a tab in private mode and switch back and forth to normal mode.

[sailfish-browser] Avoid dynamic updates of TabItem background. 

---

src/declarativewebcontainer.cpp
src/pages/BrowserPage.qml
src/pages/components/Overlay.qml
src/pages/components/OverlayAnimator.qml

Fix revealed following problems that needed to fixed in context of
this PR.
1) When browsing mode is changed, wait for a tab. Waiting is cleared from the
old model.
2) Share some logic for both model change and model count change for showing
overlay and updating the cover.
3) When switching from normal browsing to private browsing (not tabs) and back
to normal browsing enteringNewTabUrl was left to true. This made browser
page activation failing to show chrome. When the overlay is dismissed,
set the enteringNewTabUrl to false.
4) When changing from normal browsing to private browsing, the overlay was
dismissed so that chrome was revealed. This broken chrome showing animation.
So, when switching between browsing modes and overlay is dismissed it is
dismissed so that chrome is hidden. Thus, …

[sailfish-browser] Open content dimmer when private browsing mode changed. Fixes JB#30226

---

src/pages/BrowserPage.qml
tests/manual/focus-test-cases

Fixes also activating browser from new tab cover action or from the cover area.
Chrome focus handling related manual test case steps added.

[sailfish-browser] Don't bring browser to foreground if page status changes. Fixes JB#30260

---

src/pages/components/WebView.qml

This should limit the number of content updates/repaints performed by
gecko layout engine when the browser is minimized and no video content
is being played. This should significantly lower browser CPU usage when
it's swiped to the application switcher. The downside is the low fps
mode will also be enabled for pages with non-video animated content
(canvas, webgl, css animations, animated gifs etc). Currently we have no
means of recognizing pages with such content.

[sailfish-browser] Use new paint throttling functionality. Fixes JB#30183

---

org.sailfishos.browser.service
org.sailfishos.browser.ui.service
sailfish-browser.pro
src/browserservice.cpp
src/browserservice.h
src/dbusadaptor.cpp
src/dbusadaptor.h
src/sailfishbrowser.cpp

…fic calls. Contributes to JB#30203
Don't set --desktop-file=sailfish-browser.desktop in
org.sailfishos.browser.service as this means the busy-cover is shown
for non-UI calls as well as UI-specific calls. Instead, add a
separate org.sailfishos.browser.ui.service that provides the UI
functionality (openUrl() and activateNewTab()) and sets the
--desktop-file invoker argument.

[sailfish-browser] Add org.sailfishos.browser.ui service for UI-specific calls. Contributes to JB#30203

---

src/declarativewebcontainer.cpp
src/declarativewebcontainer.h
src/declarativewebutils.cpp

This patchset utilizes the new prefs added in https://github.com/nemomobile-packages/gecko-dev/pull/31 to fix our current problems with browser cover switching.

[sailfish-browser] Fix browser cover switching problems. Fixes JB#30162

---

src/pages/components/Overlay.qml

Silica Page is a focus scope so we should not focus the search field
until the browser page is active.
Before this fix virtual keyboard opened already on the tab page when
all tabs were closed and you started pop gesture from the tab page. Due
to this and virtual keyboard observer there was a white stripe blinking
at the bottom of the screen.

[sailfish-browser] Focus search field after browser page gets activated. Fixes JB#30418

---

src/pages/BrowserPage.qml
src/pages/components/Overlay.qml

This workaround adds the new tab cover action back to the cover in case
tab page is active when browser pushed to switcher. Other sub pages are not
handled (sharing and web prompts). For web prompts we should not have
new tab cover action as triggering the action would reject the prompt.
Remove this when the tab view cover is done.

[sailfish-browser] Add new tab cover action back to the tab view. Fixes JB#30443

---

src/dbmanager.cpp
src/dbmanager.h
src/dbworker.cpp
src/dbworker.h
src/declarativetabmodel.cpp
src/declarativewebpage.cpp
src/declarativewebpage.h
src/tab.cpp
src/tab.h
src/webpages.cpp
tests/auto/tst_declarativetabmodel/tst_declarativetabmodel.cpp

The first commit removes unused previousLink and nextLink properties from the `Tab` struct.
The second one simply renames DeclarativeWebPage::m_tab to DeclarativeWebPage::m_initialTab in order to stress the fact that this tab data is static and never changes after WebPage's initialization.

Minor cleanups

---

src/pages/components/WebView.qml

Increase upper limit of parsed icon, allow touch icon picking
without size, and allow high quality (large) parsed icons.

[sailfish-browser] Improve bookmark icon parsing. Contributes to JB#30209

---

src/declarativetabmodel.cpp
src/declarativetabmodel.h
src/declarativewebcontainer.cpp
src/declarativewebcontainer.h
src/persistenttabmodel.cpp
src/persistenttabmodel.h
src/privatetabmodel.cpp
src/privatetabmodel.h
src/sailfishbrowser.cpp
src/webpagequeue.cpp
src/webpagequeue.h
tests/auto/common/declarativewebcontainer.cpp
tests/auto/common/declarativewebcontainer.h
tests/auto/common/declarativewebcontainer_mock.pri
tests/auto/common/declarativewebpage.cpp
tests/auto/common/declarativewebpage.h
tests/auto/common/webview.pri
tests/auto/tst_dbmanager/tst_dbmanager.pro
tests/auto/tst_declarativehistorymodel/tst_declarativehistorymodel.cpp
tests/auto/tst_declarativehistorymodel/tst_declarativehistorymodel.pro
tests/auto/tst_declarativetabmodel/tst_declarativetabmodel.cpp
tests/auto/tst_declarativetabmodel/tst_declarativetabmodel.pro
tests/auto/tst_linkvalidator/tst_linkvalidator.pro
tests/auto/tst_webview/tst_webview.cpp
tests/auto/tst_webview/tst_webview.pro
tests/manual/testwindowopen.html

When a tab is closed and it had a parent tab, the parent tab activated
otherwise the index next to the previous active tab is activated.

[sailfish-browser] Insert new tab next to the parent tab. Fixes JB#30333

---

src/sailfishbrowser.cpp

Since the workaround breaks loading of pages like jolla.com/tablet and
the original bug it was supposed to fix (JB#11038) is no longer
reproducible let's disable it.

[sailfish-browser] Disable decoder limit workaround. Contributes to JB#30517

---

src/pages/components/LocationDialog.qml
src/pages/components/WebPopupHandler.js
src/pages/components/WebView.qml

Keep accepted/reject hosts in a hash instead of single values for accepted and rejected urls.

Revoke geolocation permissions upon app restart. 

---

src/declarativewebcontainer.cpp

Gecko's CompositorOGL can use glScissor to limit the rendering area when
compositing pages containing inline surfaces (example: iframes). In case
we've closed a view which has set some scissor box the clear operation
will not actually clear the whole surface, but only part of it. The
remaining area will have undefined content. This patch ensures that we
always reset the scissor box before clearing the surface. We currently
clear the surface manually only when no webview is opened so there is no
risk we'll affect operation of some existing CompositorOGL instance.
There shouldn't be any when the reset occurs.

[sailfish-browser] Reset glScissor state before clering the surface. Fixes JB#30882

---

src/pages/components/FavoriteGrid.qml
src/pages/components/Overlay.qml
src/pages/components/OverlayAnimator.qml

- Use animator for animating favorite grid and history list
- Don't unnecessary open virtual keyboard
- Enable clipping for the overlay only when absolutely mandatory

Set of small fixes for the overlay

---

src/browser.qml
src/declarativewebcontainer.h
src/pages/components/Overlay.qml

Currently the assumption is that when we switch to live cover page the
some content is already rendered in the web window. Unfortunately gecko
triggers first repaint after initial page reflow has been done.
Depending on content complexity this can take several seconds. To
alleviate this problem we manually fill compositing surface with white
color on several ocasions. This currently happens when gecko requests GL
context from the platform (it happens when initial EmbedLitePuppetWidget
is created) and when we get expose event and there is no active page
which can render its content. In case of bug 30162 the clear operation
triggered from EmbedLitePuppetWidget creation should ensure that no
garbage is seen when switching to a live cover. Unfortunately the actual
EmbedLitePuppetWidget …

[sailfish-browser] Trigger compositing surface clear earlier. Fixes JB#30162

---

src/pages/components/Overlay.qml

There were to cases:
1) After browser start the virtual keyboard didn't appear when url was
clicked from the toolbar
2) When to overlay content was moved and the search field was focused
afterwards the virtual keyboard didn't close propertly

[sailfish-browser] Fix virtual keyboard first time opening. Fixes JB#30972

---

src/qtmozembed/declarativewebpage.cpp

By the time session history is restored WebPage already knows
its actual URL since this is one of two conditions required to
be met when DeclarativeWebPage::restoreHistory() is called.
This actual URL needs to be provided to Gecko's DocShell
when loading session history instead of the tab's initialURL,
because Gecko may alter the URL when loading a page.
For example initialURL instead of a valid URI may contain a text
input which will be recognized as a request to search engine.
Another example would be initialURL containing just a file path
without proto. This input will be recognized as an URL of
file:// protocol. And so on...

[history] Use actual current URL when modifying session history.

---

src/core/webpages.cpp
src/declarativewebutils.cpp

Due to "low-memory" memory notification we cannot run gc upon
memory pressure. So, let the engine to run to gc when needed.
I feel that this approach works nicely with the https://github.com/nemomobile-packages/gecko-dev/pull/43

[sailfish-browser] Send "low-memory" notification to gecko on warning/critical memory level. Contributes to JB#30573

---

src/pages/BrowserPage.qml

The fact that virtual keyboard was closed for some reason does not imply
that the view is no longer focused. In the problematic case the fact
that we manually unfocused the view made the browser ignore subsequent
virtual keyboard show requests which originated from the engine. The
user is not the only source of focus changes, web pages can also modify
it's own focused element from JavaScript code.

[sailfish-browser] Don't take focus away from the page when VKBD is closed. Fixes JB#31646.

---

src/sailfishbrowser.cpp

This way there is no need to patch browser separately if you'd like to e.g. do some QML profiling. Just start the browser from command line like
> QML_DEBUGGING_ENABLED=1 sailfish-browser -qmljsdebugger=port:6666
or when profiling startup just add block.
> QML_DEBUGGING_ENABLED=1 sailfish-browser -qmljsdebugger=port:6666,block
And connect remotely to the device from the QtCreator.

[sailfish-browser] Add environment variable for enabling qml debugging. Contributes to JB#6054

---

src/core/declarativewebcontainer.cpp
src/pages/components/ResourceController.qml
src/pages/components/WebView.qml

When the screen goes off we'd like to prevent gecko from doing any
rendering. We don't want to completely pause the compositor, but we also
don't want it to execute any GL/EGL commands, especially eglSwapBuffers.
The reason for this is because it seems that on sailfish eglSwapBuffers
can currently block indefinitely when the display is turned off.
Blocked compositor thread was the main reason for huge memory leak
observed when the video was being played in the browser and the screen was
turned off. Gecko media thread produced new frame data which was never
consumed by the compositor thread. The data kept piling up until the
system run out of memory.

[sailfish-browser] Prevent gecko from rendering when screen is off. Fixes JB#31866.

---

tests/auto/tst_webview/ResourceControllerMock.qml

Noticed this while running tst_webview unit tests.

Add missing property to the ResourceController mock

---

src/core/declarativewebcontainer.cpp
src/history/declarativehistorymodel.cpp
src/history/declarativehistorymodel.h
src/history/declarativetabmodel.cpp
src/history/declarativetabmodel.h
src/history/persistenttabmodel.cpp
src/history/persistenttabmodel.h
src/history/privatetabmodel.cpp
src/history/privatetabmodel.h
src/qtmozembed/declarativewebpage.cpp
src/qtmozembed/declarativewebpage.h
src/storage/dbmanager.cpp
src/storage/dbmanager.h
src/storage/dbworker.cpp
src/storage/dbworker.h
src/storage/tab.cpp
src/storage/tab.h
tests/auto/tests.xml
tests/auto/tst_dbmanager/tst_dbmanager.cpp
tests/auto/tst_dbmanager/tst_dbmanager.pro
tests/auto/tst_declarativehistorymodel/tst_declarativehistorymodel.cpp
tests/auto/tst_declarativewebcontainer/tst_declarativewebcontainer.cpp
tests/auto/tst_persistenttabmodel/tst_persistenttabmodel.cpp
tests/auto/tst_persistenttabmodel/tst_persistenttabmodel.pro

* Don't maintain `maxTabId` in `DBManager`. Initialize tab models' `nextTabId` once upon their creation instead.
* Encapsulate `Link` creation into `DBWorker` (`TabModel` doesn't have to know about this implementation detail). Also this makes possible  dropping `TabModel`'s `nextLinkId` members and their maintenance code.
* `TabModel`'s `nextTabId` property is used nowhere - drop it from public API.
* Reduce data exchange between SQLite and DBWorker by using SQL inner joins.
* Don't include `Link` to `Tab` as a member to avoid maintaining linkId in `Tab`.
* Fully cover the storage subsystem with unit tests.

Refactor storage subsystem

---

src/history/declarativetabmodel.cpp
src/history/declarativetabmodel.h
src/pages/components/TabItem.qml
src/pages/components/TabView.qml
src/pages/components/WebView.qml
src/qtmozembed/declarativewebpage.cpp
src/qtmozembed/declarativewebpage.h
tests/auto/tst_persistenttabmodel/tst_persistenttabmodel.cpp

It's a bit of guess work but now we capture the third frame and
when the page is fully loaded. In addition, we do not clear the thumbnails
that aggresively as we are capturing only the active web page. Down
side is more or less same as it is now. For instance, if you close the
browser and leave it closed for a while, restart it, go to tab view and
you find that there out-dated thumbnails not matching the reality.
To get updates working properly, we refresh model data so (name is always
the same, like tab-1-thumb.jpg) that the new updated capture gets
rendered to the tab view.

[sailfish-browser] Improve tab thumbnailing logic. Fixes JB#23670

---

settings/Privacy.qml
src/bookmarks/bookmarkmanager.cpp
src/bookmarks/bookmarkmanager.h
src/core/declarativewebcontainer.cpp
src/core/declarativewebcontainer.h
src/core/settingmanager.cpp
src/core/settingmanager.h
src/core/webpagequeue.h
src/core/webpages.cpp
src/core/webpages.h
src/factories/factories.pri
src/factories/webpagefactory.cpp
src/factories/webpagefactory.h
src/src.pro
tests/auto/auto.pro
tests/auto/mocks/webpagefactory/webpagefactory.h
tests/auto/mocks/webpagefactory/webpagefactory.pri
tests/auto/tests.xml
tests/auto/tst_declarativebookmarkmodel/tst_declarativebookmarkmodel.pro
tests/auto/tst_declarativewebcontainer/tst_declarativewebcontainer.pro
tests/auto/tst_webpagefactory/tst_webpagefactory.cpp
tests/auto/tst_webpagefactory/tst_webpagefactory.pro
tests/auto/tst_webpages/tst_webpages.cpp
tests/auto/tst_webpages/tst_webpages.pro
tests/auto/tst_webview/tst_webview.pro

* Decouple `BookmarkManager` from `SettingsManager` (this is the reason for simplification of private data settings).
* Factor out `DeclarativeWebPage` creation to a dedicated factory object. This way it's easier to test the `WebPages` class and different scenarios of web page creation.
* Add unit tests for `WebPages`.

Move WebPage creation to a factory object.

---

defaults.pri
src/downloadmanager.cpp

Treat warnings as errors, nit pick about parentheses, and
abort build upon error.

Add stricter build flags

---

src/qtmozembed/declarativewebpage.cpp

The chrome state of web page should not affect when updating margins. Use shorter page only when contentHeight is such that gesture cannot be used to go to fullscreen mode.

[sailfish-browser] Fix entering and exiting fullscreen mode. Fixes JB#32814

---

src/core/declarativewebcontainer.cpp
src/core/declarativewebcontainer.h
src/qtmozembed/declarativewebpage.cpp
src/qtmozembed/declarativewebpage.h

Metrics are updated to contain bottomMargin and window (screen) size.
With this data all calculations can be done in embedlite-components.

[sailfish-browser] Update margins and send vkb metrics when vkb is open. Fixes JB#32818

---

src/qtmozembed/declarativewebpage.cpp

Updating bottom margin upon suspend/resume may trigger infinite
rendering loop between zero bottom margin and toolbar height margin.
In addition to above, require at least 1.5x times fullscreen height
in order to set the bottom margin. Setting bottom margin normally
triggers another content height change as the available height
changed. Normal case when bottom margin is set to zero is when
a web page has plenty of content.
Bottom margin with virtual keyboard is updated separately.

[sailfish-browser] Do not update view margins upon suspend/resume. Fixes JB#33119

---

src/declarativewebutils.cpp

We're not relying on async scroll events. So lets fire them less often than the default value (100) or B2G (15). Currently only toolbar is interested about async scroll events and it's not urgent to be updated immediately.

[prefs] Increase async scroll event throttling and timeout intervals. Contributes to JB#32858

---

src/declarativewebutils.cpp

Clear only once per frame. Without gfx.compositor.clear-context
both drawUnderlay and CompositorOGL would clear.
The embedlite.compositor.request_external_gl_context_early is not
needed EmbedLiteWindowBaseChild::CreateWidget instantiates EmbedLitePuppetWidget
and updates size for it. Due to size update the normal compositor
creation code path will get executed.
EmbedLitePuppetWidget::UpdateSize =>
EmbedLitePuppetWidget::Resize =>
EmbedLitePuppetWidget::Invalidate =>
EmbedLitePuppetWidget::GetLayerManager =>
EmbedLitePuppetWidget::CreateCompositor

[sailfish-browser] Update rendering related preferences

---

src/core/declarativewebcontainer.cpp
src/declarativewebutils.cpp
src/downloadmanager.cpp
src/downloadmanager.h
src/pages/components/BrowserContextMenu.qml
tests/auto/mocks/downloadmanager/downloadmanager.cpp
tests/auto/mocks/downloadmanager/downloadmanager.h

Adaptations basically means that now
* we don't need to wait until nsDownloadManager is initialized in order start URL download upon browser launch;
* there is no need to set URL scheme `file://` when downloading an URL to a local file target.

[sailfish-browser] Adapt to new download manager. 

---

org.sailfishos.browser.service
org.sailfishos.browser.ui.service
src/core/declarativewebcontainer.cpp
src/qtmozembed/declarativewebpage.cpp
src/sailfishbrowser.cpp

Contains two small commits. Probably still easier to review per commit.
Main problem was / is that the previous active tab got loaded when browser was launched so that there were tabs from previous browsing session. The first commit sha1 78efdd9 fixes that. The second commit sha1 41d4b76 fixes overlay flickering when browser launched via external link so that there were no tabs from previous browsing session -- overlay appears quickly on top position from where changed to chrome mode.

[sailfish-browser] Fix external link load when starting browser. Fixes JB#33892

---

src/downloadmanager.cpp
src/downloadmanager.h
src/downloadstatus.h
src/pages/components/DownloadRemorsePopup.qml
src/sailfishbrowser.cpp
src/src.pro

myapp is application metadata file that has custom handling. Thus, it should not be added to the transfer ui.

[sailfish-browser] Do not add myapp to the transfer ui. Fixes JB#34283

---

rpm/sailfish-browser.spec
src/declarativewebutils.cpp
src/declarativewebutils.h

Let's override youtube.com here so that site specific override gets triggered. Noticed that navigating from other site that was overridden to youtube.com there was just a network request. Thus, previous mapped user-agent override got picked. Will cleanup Embedlite Components side more once we get this one in. 
Furthermore, I'll add means to configure browser specific overrides in easier manner.

[sailfish-browser] Add site specific overrides. Contributes to JB#34904

---

src/sailfishbrowser.cpp

As we are not Gtk+ application and not using directly GLib
set PULSE_PROP_application.process.binary environment variable.
There must not be garbage in the application.process.binary value.

[sailfish-browser] Set application.process.binary variable for pulse audio. Contributes to JB#34695

---

src/core/declarativewebcontainer.cpp

Exit was not correctly handle on Gecko 38 if all tabs were closed (last view)
before closing the browser from the switcher.
@siteshwar review ?

[sailfish-browser] Reset MozWindow upon close event if all tabs have been closed. Fixes JB#33457

---

data/ua-update.json.in

Search result page doesn't return optimal web page. There could
something wrong elsewhere that affects layout maximum width. As
Android Firefox UA agent also reproduced wrong search result page.
Image search works better.

[user-agent] Add mobile friendlier UA for Yandex. Contributes to JB#25096

---

src/browser/declarativewebutils.cpp

See also https://github.com/sailfishos/sailfish-browser/issues/124 and
https://git.merproject.org/mer-core/embedlite-components/merge_requests/13
Using the correct AppInfo also allows use to enable asmjs. Likely
fixed by processId, processType, or/and XPCOMABI property fixes.

[sailfish-browser] Enable asmjs. Fixes JB#22349

---

src/core/declarativewebcontainer.cpp
tests/auto/mocks/qmozwindow/qmozwindow.h

See also:
https://git.merproject.org/mer-core/qtmozembed/merge_requests/8
https://git.merproject.org/mer-core/gecko-dev/merge_requests/22

[sailfish-browser] Pass QWindow size to QMozWindow on constructor. Contributes to JB#35100

---

src/core/declarativewebcontainer.cpp
src/core/declarativewebcontainer.h

The firstPaint is is not emitted correctly on web pages like ruutu.fi or dailymotion.com when those are opened to a new tab. The content dimmer does not open as first paint doesn't reach this level. What is in common with these web sites is that both contains video elements. Not sure if that play a role here but it could that e.g. that the sub tree handles the first paint (https://git.merproject.org/mer-core/gecko-dev/blob/nemo_embedlite_38/layout/base/nsPresContext.cpp#L2451). What I can see is that first paint does not reach WebBrowserChrome (https://git.merproject.org/mer-core/gecko-dev/blob/nemo_embedlite_38/embedding/embedlite/utils/WebBrowserChrome.cpp#L405).
Regardless of above, let's use QMozWindow::compositingFinished signal instead as that is coming directly from …

[sailfish-browser] Mark tab as rendered after one frame is rendered. Fixes JB#35310

---

src/core/declarativewebcontainer.cpp
src/qtmozembed/declarativewebpage.h
tests/auto/mocks/declarativewebpage/declarativewebpage.h

Embedlite-components reports domContentLoaded, telling also
if it was root frame. In practice this means that from this
point onwards there is nothing blocking browser to render.
Some references:
https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded

[sailfish-browser] Mark tab as renderer also when dom content is loaded. Fixes JB#35310

---

src/core/declarativewebcontainer.cpp
src/core/declarativewebcontainer.h
src/pages/BrowserPage.qml
src/pages/components/OrientationFader.qml
src/qtmozembed/declarativewebpage.cpp
src/qtmozembed/declarativewebpage.h

Embedlite-components reports now "embed:contentOrientationChanged"
message after content orientation has actually changed. This
commit takes that into use. Now orientation fader is opened immediately
when orientation change is effective.

[sailfish-browser] Open orientation fader after content orientation has changed. Fixes JB#35447

---

src/core/settingmanager.cpp

It's enough to check that search engines has been initialized.
@pvuorela / @jpetrell quick one to review ?

[sailfish-browser] Remove default search engine guard. Fixes JB#32815

---

src/core/declarativewebcontainer.cpp
src/core/declarativewebcontainer.h
tests/auto/mocks/qmozwindow/qmozwindow.h

See also:
https://git.merproject.org/mer-core/embedlite-components/merge_requests/17
https://git.merproject.org/mer-core/qtmozembed/merge_requests/9

[sailfish-browser] Open orientation fader aften pending orientation is effective orientation. Fixes JB#35447

---

src/qtmozembed/declarativewebpage.cpp
src/qtmozembed/declarativewebpage.h

For instance when loading images directly to a new tab, chrome does
not get domContentLoaded message from the engine.

[sailfish-browser] Mark contet loaded when page is loaded. Contributes to JB#35681

---

src/history/declarativetabmodel.cpp

When we are about to create a new tab we wait for new tab. However,
when tab is switched or new tab is created it is not needed to
wait for new tab.
This caused a glitch that occasionally that loaded website
was still on the waiting mode (blank view) even thou it was
already loaded.

[sailfish-browser] Do not wait for new tab when active tab is changed. Fixes JB#35786

---

src/pages/BrowserPage.qml
src/pages/components/Overlay.qml

If active tab was closed from tabs view, new tab was triggered from
tab view, and cancelled from overlay by dragging the overlay, the active
tab id was not activated. The error did not occur, if overlay was
cancelled by clicking the mouse area above the overlay. This fixes
the error by activating tab always when overlay is dismissed.

[sailfish-browser] Activate tab loading when overlay is dismissed. Fixes JB#35991

---

src/pages/components/Overlay.qml

Since Qt5.4 QQuickItem::opacity has been clamped between 0.0 - 1.0.
Thus, use an intermediate property for cross fading.

[sailfish-browser] Fix opacity of url text field. Fixes JB#36093

---

src/core/declarativewebcontainer.cpp
src/core/declarativewebcontainer.h
src/history/declarativetabmodel.cpp
src/history/declarativetabmodel.h
src/pages/components/Overlay.qml
tests/auto/tst_persistenttabmodel/tst_persistenttabmodel.cpp
tests/auto/tst_webview/tst_webview.cpp

@pvuorela could you review.
There are two commits.
1) Contains actual fix
2) Cleans up code that became deadcode after the fix
See also: https://github.com/sailfishos/sailfish-browser/issues/506

Soft load new active tab when a tab is removed

---

src/browser/browser.cpp

We accidentally changed profile path when updating browser
to use common WebEngine. Thus, previously saved passwords,
caches, preferences got lost.

[sailfish-browser] Fix browser profile path. Fixes JB#36500

---

src/browser/declarativewebutils.cpp
src/browser/downloadmanager.cpp
src/core/declarativewebcontainer.cpp
src/core/settingmanager.cpp
src/pages/components/ConfigDialog.qml
src/pages/components/DownloadMenuItem.qml
src/pages/components/ResourceController.qml
tests/auto/mocks/declarativewebutils/declarativewebutils.cpp
tests/auto/mocks/qmozcontext/qmozcontext.h
tests/auto/mocks/webengine/webengine.cpp
tests/auto/mocks/webengine/webengine.h
tests/auto/mocks/webengine/webengine.pri
tests/auto/mocks/webengine/webenginesettings.cpp
tests/auto/mocks/webengine/webenginesettings.h
tests/auto/tst_declarativewebcontainer/tst_declarativewebcontainer.cpp
tests/auto/tst_declarativewebcontainer/tst_declarativewebcontainer.pro
tests/auto/tst_webpages/tst_webpages.cpp
tests/auto/tst_webpages/tst_webpages.pro
tests/auto/tst_webutils/tst_webutils.pro
tests/auto/tst_webview/tst_webview.cpp

More or less find & replacing deprecated method calls. This also fixes one signal name for QMozContext mock (2nd commit), fixes WebUtils unit tests (3rd commit), and fixes WebPage unit tests  (4th commit).
There are still references to QMozContext but at least logs are no longer full of deprecated API calls.

[sailfish-browser] Cleanup deprecated mozcontext calls. Fixes JB#36499

---

tests/auto/tst_declarativewebcontainer/tst_declarativewebcontainer.pro

This test case should have been using mock rather than linking
to the WebEngine.

[sailfish-browser] Fix crashing tst_declarativewebcontainer

---

src/pages/components/WebView.qml
src/qtmozembed/declarativewebpage.cpp

When browser is cover by another application and user peeks
the top most application a bit so that switcher becomes visible also
browser activates and continues rendering. However, this peek
should not update content margins which can happen if
contentHeight changes.
This also moves toolbar / chrome handling to C++ side. Chrome gesture
is now enabled / disabled based forcedChrome property. Chrome is
reset when nagivating from one web page to another.
See also : https://git.merproject.org/mer-core/qtmozembed/merge_requests/27

[sailfish-browser] Do not allow margins updates when browser is in background. Fixes JB#35305

---

src/core/declarativewebcontainer.cpp

This pauses compositor when we are not ready to render making
LayerManagerComposite to return early from
LayerManagerComposite::BeginTransaction.
Occasionally we can see "chessboard" like garbage textures when you start loading web pages. Not sure if all error are caused due to this. Nevertheless, we should pause the gecko compositor.

[sailfish-browser] Suspend / resume rendering when ready to paint changes. Contributes to JB#35379

---

src/pages/components/WebView.qml

As there are now atYBeginning and atYEnd properties, let's use those
to fix some minor toolbar issue.
1) Pan content to the beginning so that you pan only half of the toolbar
height on each pan gesture (or less). Toolbar was not shown when content
reached top if it was hidden.
2) Pan content to the end so that you pan only half of the toolbar height
on each pan gesture (or less). When there's enough content (chrome gesture
was enabled) and you reached, toolbar should animate away.
3) If web content is scrolled from JavaScript (I count also anchors),
toolbar was not animated in when content reached beginning. Similarly toolbar
was not animated away when content reached end.

[sailfish-browser] Show / hide toolbar when content hits edge. Fixes JB#14628

---

src/pages/components/WebView.qml

When we are loading a web page, atYBeginning and/or atYEnd might change
so that content reaches beginning/end while in reality content loading is
about to start. Thus, guard statements with domContentLoaded property.

[sailfish-browser] Do not change chrome state before dom content is loaded. Contributes to JB#14628

---

src/pages/components/WebView.qml

Give focus to the other window and hide virtual keyboard.
See also: https://github.com/sailfishos/sailfish-components-webview/pull/18

[sailfish-browser] Close vkb when opening context menu. Contributes to JB#36163

---

src/storage/dbworker.cpp

This commit adds visited count to the history search. It should have been there from day one.
@jpetrell @chriadam review ?

[sailfish-browser] Show frequently visited web pages at top of history search. Fixes JB#36478

---

src/pages/components/TextSelectionController.qml

This improves phone number selection. The error that users saw were such that
selected phone number didn't show "Call" icon in the toolbar. The "Call" icon
was shown only after either of the selection handles were moved a bit.

[sailfish-browser] Update selected text status when cellular is enabled. Fixes JB#37557

---

src/pages/BrowserPage.qml
src/pages/components/WebView.qml

This commit adds a clearSelection wrapper to the WebView that can
called whenever text selection needs to be cleared.
Text selection is also cleared when BrowserPage becomes inactive.

[sailfish-browser] Clear text selection when receiving an external url. Fixes JB#37947

---

src/history/declarativetabmodel.cpp

Always chop trailing slash if fragment or query do not exist. The
QUrl::StripTrailingSlash doesn't remove trailing slash if path is "/".
So this fixes "https://sailfishos.org/about" or "https://sailfishos.org"
kind of urls not to create new tab if the tab exists already.
Can be tested e.g. by using:
xdg-open https://sailfishos.org
This effects only external link handling.

[sailfish-browser] Improve tab matching when activating a tab. Contributes to JB#38635

---

tests/auto/test_common.pri
tests/auto/tst_declarativehistorymodel/tst_declarativehistorymodel.pro
tests/auto/tst_declarativewebcontainer/tst_declarativewebcontainer.pro
tests/auto/tst_persistenttabmodel/tst_persistenttabmodel.pro
tests/auto/tst_webpagefactory/tst_webpagefactory.pro
tests/auto/tst_webpages/tst_webpages.pro
tests/auto/tst_webutils/tst_webutils.pro

I couldn't determine from the git history why there would be libraries in LFLAGS. As is a strict left-to-right resolving linker fails with:
[  344s] g++ -lgtest -lgmock -Wl,-O1 -o tst_declarativehistorymodel testobject.o declarativewebpage.o declarativewebcontainer.o browserpaths.o dbmanager.o dbworker.o link.o tab.o declarativetabmodel.o persistenttabmodel.o privatetabmodel.o linkvalidator.o declarativehistorymodel.o tst_declarativehistorymodel.o moc_testobject.o moc_declarativewebpage.o moc_declarativewebcontainer.o moc_dbmanager.o moc_dbworker.o moc_declarativetabmodel.o moc_persistenttabmodel.o moc_privatetabmodel.o moc_declarativehistorymodel.o   -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Sql -lQt5Test -lQt5Core -lGLESv2 -lpthread 
[  345s] declarativewebcontainer.o: In function …

[sailfish-browser] Move libraries from QMAKE_LFAGS to LIBS. Contributes to JB#38751

---

src/browser/declarativewebutils.cpp

Shorten UA update interval to two every second day.

[sailfish-browser] Shorten UA update interval. Contributes to JB#39970

---

data/prefs.js

This makes it sure that preferences are available for the Gecko compositor
thread when it requests gl context.

[sailfish-browser] Write rendering preferences to prefs.js. Contributes to JB#39851

---

src/browser/browser.cpp
src/browser/declarativewebutils.cpp
src/browser/declarativewebutils.h

Unknown mime type triggers still misleading download notification even though
the file is already in the file system.

[browser] Improve local file handling when opening a local externally. Contributes to JB#40671

---

src/core/declarativewebcontainer.cpp
src/core/inputregion.cpp

This might be take it or leave it stuff in the end. I was seeing a crash in the DeclarativeWebContainer code but I can't see anything actually wrong with the original version so its possible that despite having been rebuilt in OBS I was pulling a stale version and the fix was that I had a guaranteed build against Qt 5.9.
Likewise, the MOUSE_REGION window property would ideally be deprecated since its almost functionally identical to the window mask. The problem as it turns out is its not possible to create a QRegion from a rectangle with a 0 width or height and an empty QRegion is interpreted as an infinite region and all touch events to the web view are blocked when the crome is hidden. Ideally we'd hide the chrome surface too in that circumstance but that's likely to have knock on …

[browser] Fix Qt 5.9 compatibility issues. Contributes to JB#42592

---

oneshot.d/browser-update-default-data

Busybox does not support perl regex on grep. We want to be compatible
with busybox as well as GNU grep.

[oneshot] Do not use perl regex. Contributes to JB#40843

---

data/ua-update.json.in

[browser] Return back "Maemo" for google.com domain UA override. Fixes JB#45164

---

src/main.cpp

Crash guard is normally disabled on nightly builds. As we're running
with our tweaks should be perfectly ok to run as a "nightly" even though
the build is a release build.

[browser] Disable crash guard and prefer egl for webgl. Fixes JB#44402

---

data/ua/45.9.1/ua-update.json

The Firefox version of Twitter is currently failing to load with a 'Sorry, We did something wrong' error. This change drops back to the old mobile site, and gives a warning, but at least shows the content.

[UA] Workaround user-agent for twitter.com load failure. JB#46293

---

rpm/sailfish-browser.spec
src/core/declarativewebcontainer.cpp
src/core/declarativewebcontainer.h
src/pages/components/CertificateInfo.qml
src/pages/components/CertificateLabel.qml
src/pages/components/Overlay.qml
src/pages/components/OverlayAnimator.qml
src/pages/components/ToolBar.qml
src/qtmozembed/declarativewebpage.cpp
src/qtmozembed/declarativewebpage.h
tests/auto/mocks/declarativewebcontainer/declarativewebcontainer.h
tests/auto/mocks/declarativewebpage/declarativewebpage.h
tests/auto/mocks/qmozsecurity/qmozsecurity.h
tests/auto/mocks/qmozsecurity/qmozsecurity.pri
tests/auto/tst_declarativewebcontainer/tst_declarativewebcontainer.pro
tests/auto/tst_webpages/tst_webpages.pro
tests/auto/tst_webview/tst_webview.pro

Adds a new button to the toolbar that gives immediate feedback on the
SSL/TLS security status. Clicking on the button displays on overlay with
more info about the TLS certificate and security of the page being
viewed, as provided by gecko (via qtmozembed).

Display SSL/TLS security info to the user

---

data/ua-update.json.in

This commit also simplifies twitter.com override.

[ua] Make apkpure.com to be identified as mobile. Fixes JB#47744

---

src/core/core.pri
src/core/declarativewebcontainer.cpp
src/core/declarativewebcontainer.h
src/pages/components/Overlay.qml
src/pages/components/OverlayAnimator.qml

When the browser opens for the first time there is no page to display,
and the user should be presented with the URL entry field open.
Previous changes which introduced the TLS panel broke this behaviour.
These changes fix the regression.
The problem seems to be twofold. First, the atTop/atBottom state
behaviour changed (because panels with multiple sizes were introduced,
meaning it was possible to change from a large panel size to a smaller
panel size and still be atTop). The initial URL entry field relies on a
switch from atTop = false to atTop = true in order to trigger a
searchField.requestingFocus change in Overlay.qml. Second, the
initial _showUrlEntry entry also has to be true in order to trigger this
requestingFocus state change. This will revert to false as soon as
atBottom …

Ensure empty browser opens with URL entry

---

rpm/sailfish-browser.spec

…butes to JB#47875
To allow the overlayBackgroundColor to be queried from within the C++
code. This should have been included in the previous commits as it's
needed to allow the packages to build.

[sailfish-browser] Add sailfish-silica as a build requirement. Contributes to JB#47875

---

src/pages/components/FavoriteContextMenu.qml
src/pages/components/FavoriteGrid.qml

This commit also removes obsoleted animated removal call.

[sailfish-browser] Use remorse delete for favorites. JB#48357

---

src/pages/components/WebView.qml

screen. Fixes JB#45096
When the device unlocks and moves to the Events screen, the home
screen is briefly active before lipstick moves to the Events screen,
and at this point the browser window visibility is still
QWindow::FullScreen, so the WebView foreground binding is true.
However the BrowserPage raises the window whenever foreground=true, so
this causes the window to be raised when lipstick is actually moving
to another screen.
To prevent the unnecessary raise(), don't set foreground=true when the
application is not active.

[sailfish-browser] Don't foreground browser when unlocking to another screen. Fixes JB#45096

---

rpm/sailfish-browser.spec
src/browser.qml

Normally application windows which hide the application background are
considered opaque, overwrite this default for the chrome window which is
stacked above the browser window.

[browser] Identify the chrome window as not being opaque. Contributes to JB#49482

---

src/browser/declarativewebutils.cpp

The "security.tls.version.min" is defaults to 1 in security-prefs.js.
Hence, not needed on the browser side.
The pref "security.csp.speccompliant" no longer exists. So we
can just remove it.

[browser] Cleanup security preferences. JB#50423

---

src/browser/browser.cpp
src/browser/declarativewebutils.cpp
src/browser/declarativewebutils.h

The startupCache needs to be removed if it's stale (e.g. after component
installation). The code to do this has been moved into xulrunner and so
is no longer needed here.
This change effectively reverts commit
469d6a7dfe43efacf866d7f28d32eda24f3a0a9d

Remove startupCache removal code

---

tests/manual/testpage.html
tests/manual/testtouchaction.html
tests/manual/testtouchclick.html

Adds two new test pages:
1. Touch action test page, for testing the touch-action css property.
2. Touch/click test page. On desktop clicking on the items will generate
mouse but not touch events. On mobile pressing the items should trigger
both touch and mouse events.

[sailfish-browser] Add touch-related test pages. Contributes to JB#50875

---

common/browserapp.cpp
common/browserapp.h
common/browserapp.pri
oneshot.d/browser-cleanup-startup-cache
oneshot.d/browser-update-default-data
org.sailfishos.browser.captiveportal.service
rpm/sailfish-browser.spec
sailfish-browser-captiveportal.desktop
sailfish-browser.pro
src/BrowserWindow.qml
src/browser/browser.cpp
src/browser/browserservice.cpp
src/captiveportal.qml
src/core/declarativewebcontainer.cpp
src/main.cpp
src/pages/CaptivePortalPage.qml
src/pages/captiveportal.js
src/pages/components/CaptivePortalOverlay.qml
src/pages/components/CaptivePortalToolBar.qml
src/pages/components/WebView.qml
src/qtmozembed/declarativewebpage.cpp
src/src.pro
tests/auto/tst_declarativewebcontainer/tst_declarativewebcontainer.pro
tests/auto/tst_webpages/tst_webpages.pro
tests/auto/tst_webview/tst_webview.pro

This pull request adds support for starting browser with simplified UI and a separate profile enabled by -captiveportal flag, which is going to be used for opening Wi-Fi captive portal pages with separate browser profile to avoid leaking browser data.

[browser] Add a special mode for WLAN captive portals. Contributes to JB#40777

---

sailfish-browser-captiveportal.desktop

A follow up to #701. This hides captive portal browser icon from application grid which was left for testing.

[sailfish-browser] Hide captive portal browser from application grid. Contributes to JB#40777

---

README.md

Just looked at the repository and the referenced blog no longer exists. I couldn't find it anywhere else so I linked it via the wayback machine.

Replace dead link in readme with a copy from the wayback machine

---

tests/manual/testcss.html
tests/manual/testpage.html

The page just has a couple of tests:
1. CSS font tests.
2. CSS shapes (since the features straddle ESR60 and ESR62).
Probably more CSS tests should be added in the future.

Add a CSS test page

---

tests/manual/testhtml5audio.html

The audio files being linked to by the audio test page were missing.
This updates the URLs to point to valid locations.
An audio player for FLAC is also now included.

Update audio test page

---

src/pages/BrowserPage.qml

In case the contentItem does not exist, the fullscreen mode cannot be
true either. Fix showing up toolbar accordingly.

[browser] Show toolbar properly when entering back to browser page. Fixes JB#45651

---

tests/manual/testbuttontarget.html
tests/manual/testpage.html

Adds a manual test page for testing whether child elements within a
button element can be touch targets.
Prior to mozilla 66 the button was always the target. This was fixed
from 66 onwards to allow child elements to claim click, hover, etc.
events as well. The new behaviour matches that of other browsers and is
expected by some sites.
See mozilla bug 1089326.

Add touch button target test page

---

tests/manual/testmargindrift.html
tests/manual/testpage.html

Adds a manual test page that's intended to help testing various aspects
of page display with page margins and the toolbar:
1. Are fixed elements correctly moved if the toolbar/keyboard is open.
2. Does element touch selection drift when the page is scrolled.
3. Are all elements (fixed and scrollable) fully visible on the page.

Add touch drift/browser margins test page

---

src/pages/PrivacySettingsPage.qml
src/pages/components/BookmarkEditDialog.qml
src/pages/components/FavoriteContextMenu.qml
src/pages/components/SecondaryBar.qml

We have no technical differences for bookmark and favorite now. Same model used
However, the separate BookmarkPage is the bookmark for the user.
It is necessary to rename the places where are "favorite" words to "bookmark",
where is it clear. In the future, these will be different models

[sailfish-browser] Rename favorites to bookmark. Fixes JB#51984

---

src/pages/BookmarkPage.qml
src/pages/HistoryPage.qml
src/pages/components/SecondaryBar.qml

When panning content search field and bookmarks headers should be moving as well.
Also move HistoryPage and BookmarkPage to "pages" directory.

[sailfish-browser] Move header from page root to SilicaListView. Fixes JB#52084

---

src/pages/components/ResourceController.qml

States "online" and "ready" mean connman is online.
If online check fails then connman state is "ready".

[sailfish-browser] Fix online network link status. Contributes to JB#45654

---

common/browserapp.cpp
oneshot.d/browser-cleanup-startup-cache
oneshot.d/browser-move-data-to-new-location
oneshot.d/browser-update-default-data
rpm/sailfish-browser.spec
sailfish-browser.pro
src/browser/browser.cpp

Move browser and captive portal profiles to .cache/org.sailfishos/sailfish-browser
and .cache/org.sailfishos/sailfish-browser-captiveportal respectively
to better adhere to freedesktop standards.
Adds oneshot that can be removed after it's been in one stop release.

[browser] Move data to new location. JB#51740

---

backup-unit/browserunit.cpp

This moves the files around in the in memory copy of the archive before
restoring it. This doesn't modify the archive itself because it is
mounted with nosave option.

[sailfish-browser] Fix restoring old backups. Fixes JB#52318

---

apps/browser/browserservice.cpp
apps/browser/browserservice.h
apps/browser/qml/pages/BrowserPage.qml
apps/browser/qml/pages/components/Overlay.qml
apps/core/declarativewebcontainer.cpp
apps/core/declarativewebcontainer.h

Privileged check doesn't work inside sandbox. There is little reason to
keep requestTab privileged API. This allow it for unprivileged clients.
It would be bad to allow closeTab for all. Mark the process that called
requestTab as owner of the tab and allow the owner to call it.

Allow some D-Bus APIs for unprivileged clients

---

org.sailfishos.browser.service
org.sailfishos.browser.ui.service
org.sailfishos.captiveportal.service

Use invoker for correct cgroup delegation on D-Bus activation.

[sailfish-browser] Use invoker on D-Bus activation. Contributes to JB#52187

---

apps/browser/qml/pages/SettingsPage.qml

Now as the browser settings are part of the Browser app itself the
dconf for the search engine is not mandatory either. However, that
still splits nicely engine initilaization and settings page. To be
seen what to do with it.

[browser-settings] Clean current search engine index handling. JB#40380

---

apps/browser/qml/pages/BrowserPage.qml

Count changed signal caused state change in overlay.animator and hid
the toolbar. Don't do state change if webView is waiting for new tab.

Don't hide toolbar while waiting for new tab.

---

oneshot.d/browser-update-default-data

Clearing the general.useragent.override user pref was a temporary
addition intended to be removed on the next upgrade.
Reverts 426e60bed917d46e2191f6f1b15ebe22dacfd681

Remove clearance of general.useragent.override user pref

---

apps/browser/qml/pages/BrowserPage.qml
apps/core/declarativewebutils.cpp

It is no longer required to do this here, its already in the PickerOpener.

[sailfish-browser] Remove handling downloadpicker from WebEngine. Contributes to JB#53798

---

apps/browser/browser.pro
apps/captiveportal/captiveportal.pro
apps/shared/shared.pri

To ensure lupdate runs over the QML files in the shared folder.

[sailfish-browser] Add shared folder to translations

---

apps/browser/bookmarks/bookmarkfiltermodel.cpp
apps/browser/bookmarks/bookmarkfiltermodel.h

To be added on top of https://github.com/sailfishos/sailfish-browser/pull/798, so will be WIP until that has been merged.
A small glitch meant that favicons downloaded when a favourite was added
could trigger a `dataChanged()` signal while the model was being
constructed, which interacted badly with the accept count.
This change ensures that `filterAcceptRow()` calls can be received in any
order and still respond correctly.

Ensure BookmarkFilterModel::filterAcceptsRow() can be called out-of-order

---

sailfish-browser.desktop

Allow browser to access documents on removable, external data storages
such as USB sticks and SD cards.

Add RemovableMedia Sailjail permission

---

apps/browser/qml/pages/EditLoginPage.qml
apps/browser/qml/pages/LoginsPage.qml
apps/browser/qml/pages/SettingsPage.qml

Adds a page accessible from the settings for managing stored logins
(usernames and passwords).
This is still WIP, but it may already be useful for testing the models.

Add login management settings page

---

apps/shared/ResourceController.qml

`WebEngine.initialized` is now a property (see qtmozembed) so we can use it as such.

Use WebEngine.initialized property

---

apps/browser/qml/pages/SettingsPage.qml
apps/browser/qml/pages/components/AddHomePageDialog.qml

If two or more ConfigurationValue instances are duplicated simultaneously, the values are not correctly updated for sandboxed apps. There is no problem if only a single instance exists at a time.
This change ensures the ConfigurationValue for the home page is shared rather than duplicated when the folder picker is pushed.
This doesn't address the underlying Sailjail issue, however even once addressed, I believe this change is appropriate anyway (since it shouldn't be necessary to use DBus to send data within the same app).

Avoid duplicating ConfigurationValue

---

apps/browser/browser.pro
apps/captiveportal/captiveportal.pro

There are QML files shared by both the browser and captiveportal subprojects. If both projects run them through the translator there will be duplicate IDs, which unnecessarily increases work for the translators.
This change ensures the shared files are only parsed once.

[browser] Avoid duplicating strings across subprojects. Fixes JB#54618

---

apps/browser/qml/pages/EditLoginPage.qml
apps/browser/qml/pages/LoginsPage.qml
apps/browser/qml/pages/SettingsPage.qml
apps/browser/qml/pages/components/SecureAction.qml

The Logins list in Settings allows access to the user's stored account passwords, either by copying the password or editing it. This change introduces a device lock gate, so that the user has to perform device authentication (e.g. PIN, fingerprint) before the passwords will be shown.
Once authenticated, the user won't be asked again until the Logins list page has been exited.
Builds on top of #836, so only the latest commit (a07b351e0f4bb853475766e82fe6bae15884212c) contains changes from that.

Add device lock gate for password access

---

sailfish-browser.desktop

Replace separate Documents, Downloads, Music, Pictures and Videos
permission with UserDirs. This covers all the locations on user's $HOME
that should be available for the browser.

Replace separate permissions with UserDirs.

---

apps/browser/qml/pages/components/AddToAppGridDialog.qml
apps/browser/qml/pages/components/BookmarkEditDialog.qml
apps/browser/qml/pages/components/BookmarkItem.qml
apps/browser/qml/pages/components/FavoriteGrid.qml
apps/browser/qml/pages/components/ToolBar.qml

Rolls up a few changes:
1. Remove close button from the toolbar.
With the popup menu replacing the toolbar, the button can no longer be
pressed to close the current tab. This removes the button, the tab can
still be closed from the tab grid.
2. Ensure tab number is visible in private mode.
When in private mode the tab icon on the toolbar has inverted colours.
This change inverts the text colour so it's still visible on top of the
icon.
3. Fix bookmark edit dialog header.
The missing header was causing the dialog fields to overlap with the
action buttons at the top of the page. This adds a header to fix it.
I can split them into separate PRs if that would make it easier to handle.
Still needs an OMP bug ref associated with it.

Remove close button from the toolbar

---

apps/browser/qml/pages/SettingsPage.qml

Previously it was not clear what did happen after tabs were closed.
This commit changes description text to describe implications by saying
that "When Browser is started next time, selected Home page will be loaded".

[browser] Cleanup 'Close all tabs on exit' description. Fixes JB#51764 OMP#JOLLA-165

---

50-sailfish-browser.conf
data/70-browser.conf
org.sailfishos.browser.service
org.sailfishos.browser.ui.service
rpm/sailfish-browser.privileges
rpm/sailfish-browser.spec
sailfish-browser.desktop
sailfish-browser.pro
tests/manual/test-sailfish-browser.desktop

Instantiate browser booster on user session startup.
Modify exec lines in desktop and D-Bus autostart files so that
browser booster is used for launching.
Remove booster privilege configuration that is no longer needed.
Signed-off-by: Simo Piiroinen <simo.piiroinen@jolla.com>

[sailfish-browser] Use sandboxed booster. JB#54788 OMP#JOLLA-213

---

apps/browser/qml/pages/components/PopUpMenu.qml

The gesture relies on vertical overscroll, so dragging must be enabled
even when the height of the menu content is not greater than the menu
itself.

[sailfish-browser] Fix popup menu drag to close with small menus. Fixes JB#54843 OMP#JOLLA-228

---

apps/browser/qml/pages/BrowserPage.qml
apps/browser/qml/pages/components/Overlay.qml

There are following cases that should be covered when triggering "Search"
from the Top Menu:
1) Browser not running and all tabs were closed on previous browsing session
2) Browser not running and there are tabs from the previous browsing session
3) Browser running with tabs and browsing view active
4) Browser running with tabs and tabs view active
5) Browser running without tabs and browsing view active
6) Browser running without tabs and tabs view active
I didn't see JB#53613 regressing due to this (sha1 d70d01bc4669d96)

[browser] Focus url field when new tab view requested. Fixes JB#54805 OMP#JOLLA-240

---

apps/browser/qml/pages/HistoryPage.qml
apps/browser/qml/pages/components/HistoryItem.qml
apps/browser/qml/pages/components/HistoryList.qml
apps/browser/qml/pages/components/Overlay.qml

Added a fix for opening context menu of the history list.
Also added menu items (open in incognito tab, add to bookmarks) in accordance with the design:
It should be noted that when saving to bookmarks, the standard icon is always used.

[sailfish-browser] Add to history list: call context menu, open in incognito tab, save to bookmarks. Fixes JB#54882

---

apps/storage/dbmanager.cpp
tests/auto/tst_dbmanager/tst_dbmanager.pro
tests/auto/tst_webpagefactory/tst_webpagefactory.pro

SettingManager::clearHistory() calls
DBManager::clearHistory() calls
DBWorker::clearHistory() emits historyAvailable() which triggers
DeclarativeHistoryModel::historyAvailable() which calls
DeclarativeHistoryModel::updateModel().
Thus, DeclarativeHistoryModel::clear() is never invoked in this
codepath.  We cannot simply clear the favicon for any url which is
no longer represented in the history model within updateModel()
since historyAvailable() will be emitted with limited data (due to
the LIMIT in the query in the general case, or due to the WHERE
in the dynamic filter case).  As such, we need to ensure that we
manually clear the history favicons when DBManager::clearHistory()
is called.

[browser] Remove favicons when clearing history. Contributes to JB#54864 OMP#JOLLA-237

---

data/prefs.js

If the "intl.locale.requested" preference is unset, gecko will default
to only a single fallback locale. If it's set to an empty string, it
will instead set the locale based on the OS setting.
This adds the preference as an empty string to the default preferences.

Activate multiple available locales. JB#54830 OMP#JOLLA-222

---

apps/browser/qml/pages/SettingsPage.qml

Rename "default home page" to "start view", "custom website" to "web page" in contextMenu.
Remove trim() method from title of start view combobox menu, it had already trimmed when
sets to config value.

[browser] Update contextMenu terminology in settings page for "home page". Contributes to JB#54904

---

apps/shared/ResourceController.qml
rpm/sailfish-browser.spec

Introduces the ConnectionHelper to allow the network selector to be
triggered when the "network-enable" notification is sent.
NetworkManager was previously used for determining the  online status.
ConnectionHelper exposes the same functionality (it's a very light
wrapper around NetworkManager in fact), so ConnectionHelper is now used
for this instead.

Switch from NetworkManager to ConnectionHelper. JB#54831 OMP#JOLLA-223

---

apps/browser/qml/pages/HistoryPage.qml
apps/browser/qml/pages/components/HistoryList.qml
apps/browser/qml/pages/components/Overlay.qml

Move placeholder and change condition for enabled property.
Make SearchField enabled when history model is empty.

[browser] Move placholder from HistoryPage to the HistoryList. Fixes JB#55176

---

data/ua-update.json
data/ua-update.json.in
data/ua/60.0/ua-update.json

The site ok.ru show mobile version.
The zoom.us doesn't show the error "The Operating System or the version of Operation System running is not supported" anymore.
The corp.express doesn't redirect to mobile version when opening desktop mode anymore.

[ua] User agent fix for ok.ru, zoom.us and corp.express. Fixes JB#55234

---

sailfish-browser.desktop

Sharing is allowed by default, separate permission is not needed.
Signed-off-by: Simo Piiroinen <simo.piiroinen@jolla.com>

[sailfish-browser] Remove unneeded Sharing permission. JB#55380

---

apps/browser/qml/pages/BrowserPage.qml
apps/core/browser.cpp
apps/core/browser_p.h
apps/core/closeeventfilter.cpp
apps/core/closeeventfilter.h
apps/core/declarativewebcontainer.cpp
apps/core/declarativewebcontainer.h

The full set of PRs related to this:
1. https://github.com/sailfishos/gecko-dev/pull/9
2. https://github.com/sailfishos/qtmozembed/pull/3
3. https://github.com/sailfishos/sailfish-browser/pull/897 (this)

[sailfish-browser] Recreate browser window from existing process on browser launch. Contributes to JB#54813

---

apps/shared/ResourceController.qml

This partially reverts changes made in 8014ee097530c4c902. In that
change, ConnectionHelper was introduced to allow the "Select Wifi
network" dialog to be triggered. In order to simplify the code, the
online status check was also switched to using ConnectionHelper.
It turns out this interferes with the captive portal, since this relies
on the "ready" state to be considered equivalent to "online". The
ConnectionHelper didn't respect this.
This change therefore switches back the online status check to using the
previous NetworkManager approach.
Setting as draft until I've tested the change.

Use connectivity to establish online status. Fixes JB#55628 OMP#JOLLA-401

---

apps/browser/qml/pages/SettingsPage.qml
apps/browser/qml/pages/components/BrowserComboBox.qml

The BrowserListItem isn't good for this case, because this should be highlighted by default for currentIndex.
So, it's good to use ComboBox instead and move general code to BrowserComboBox for avoiding duplicated code.
Set save destination by default if the user reject to choose download folder.

[browser] Use combobox also for save destination. Fixes JB#55580

---

apps/browser/qml/pages/HistoryPage.qml
apps/browser/qml/pages/components/HistoryItem.qml
apps/browser/qml/pages/components/HistoryList.qml
apps/browser/qml/pages/components/Overlay.qml
apps/browser/qml/pages/components/PopUpMenuItem.qml

Add a call to function of saving bookmarks in the PopUpMenuItem element.
Add use of favicon when saving to bookmarks.

[sailfish-browser] Fix adding link to bookmarks if opening history page via popup menu. Fixes JB#55694

---

apps/core/closeeventfilter.cpp

Terminate the browser process after all downloads have finished, only if it is being closed.

[sailfish-browser] Fix browser termination when all downloads are completed. Fixes to JB#55836

---

apps/shared/WebView.qml

Scale the thumbnail size to fit the largest size that will fit the
window size rather scaling to fit the width which can produce heights
larger than the window in landscape.

[sailfish-browser] Fix invalid thumbnail sizes for tabs being requested. JB#55754 OMP#JOLLA-417

---

tests/manual/testlogging.html
tests/manual/testpage.html

This is just a really simple test page. It calls various console logging methods on load.
To be deployed to:
https://browser.sailfishos.org/tests/testlogging.html

Add test page for javascript log output. JB#55880 OMP#JOLLA-435

---

apps/core/declarativewebcontainer.cpp
apps/core/declarativewebcontainer.h
apps/core/settingmanager.cpp
apps/core/settingmanager.h
tests/auto/tst_logins/tst_logins.cpp
tests/auto/tst_webview/tst_webview.cpp

The initialisation is needed to connect up change signals from the Search Provider DConf value. Hence prior to this change, if the user switched Search Provider, it wasn't applied until the next browser restart. This change fixes this.
This is a small regression from 68b52fef7fd89c12ddfe423 which removed the code initialising the `SettingManager` (for valid reasons, but it left it uninitialised).

Initialise SettingManager at start up. Fixes JB#56200 OMP#JOLLA-507

---

apps/browser/qml/browser.qml
apps/browser/qml/pages/BrowserPage.qml
apps/browser/qml/pages/components/Overlay.qml

Adds a connection to ensure that the browser cover always gets updated whenever the number of tabs changes. Previously the switch from zero to one tabs (which triggers a cover change) wasn't being picked up, leaving the cover in an incorrect state.

Update browser cover on tab changes. Fixes JB#56224 OMP#JOLLA-513

---

apps/browser/qml/pages/PrivacySettingsPage.qml
apps/core/settingmanager.cpp
apps/core/settingmanager.h

Change checkbox for clearing "cookies" to "cookies and site data".
Change clearCookies() method to clearCookieAndSiteData().

[sailfish-browser] Replace clearing of "cookie" with "cookie and site data" in PrivacySettingsPage. JB#56151

---

data/ua-update.json.in

* [ua] Drop thomann.de user-agent override. Fixes JB#56016 OMP#JOLLA-461
* For reference: JB#53530
* [ua] Drop ask.com user-agent override. JB#56016 OMP#JOLLA-461
* For reference JB#51725
* [ua] Drop hymy.fi and alibi.fi user-agent overrides. JB#56016 OMP#JOLLA-461
* [ua] Drop verkkokauppa.com user-agent override. JB#56016 OMP#JOLLA-461
* [ua] Cleanup user-agent overrides that matches to default. JB#56016 OMP#JOLLA-461

Cleanup obsoloted user-agent overrides

---

apps/qtmozembed/declarativewebpage.cpp
apps/qtmozembed/declarativewebpage.h

QImage (Qt 5.6) writes directly to the target file when saving, so if an
Image item happens to try and read from it at the same file then that
may fail because the file is incomplete.
The concurrent read/write may happen because an existing tab is being
updated, or because saveToFile() was dispatched to a thread and the user
could have switched tabs in the interim leading to the data being
written to the thumbnail of a different tab.

[sailfish-browser] Fix error reading tab thumbnails from cache. Fixes  JB#56298 OMP#JOLLA-533

---

apps/history/declarativetabmodel.cpp

This commit fixes new tab creation with proper parent id when requested
by web content itself (for many cases). Problem that persists after this
is that there can be wrong parent browsing context passed to the created
child view causing nsWindowWatcher to assert.
There's one follow up change coming after this one.

[browser] Request new tab (page) before adding to the model. JB#56631 OMP#JOLLA-569

---

apps/core/declarativewebcontainer.cpp
apps/core/declarativewebcontainer.h
apps/core/webpages.cpp
apps/core/webpages.h
apps/factories/webpagefactory.cpp
apps/factories/webpagefactory.h
apps/history/declarativetabmodel.cpp
apps/history/declarativetabmodel.h
apps/qtmozembed/declarativewebpage.cpp
apps/qtmozembed/declarativewebpage.h
apps/qtmozembed/declarativewebpagecreator.cpp
apps/qtmozembed/declarativewebpagecreator.h
apps/shared/WebView.qml
apps/storage/tab.cpp
apps/storage/tab.h
tests/auto/mocks/declarativewebpage/declarativewebpage.h
tests/auto/tst_persistenttabmodel/tst_persistenttabmodel.cpp
tests/auto/tst_webpagefactory/tst_webpagefactory.cpp

This commit renames webpage's setInitialTab to setInitialState and
sets all initial state related attributes there.
Setting initial state happens right before initialize() is called.
Browsing context is added to the tab and parent id has been moved to
the tab so that those get carried to the initialization. This implies
that parentId got removed from the methods and signals. Further, to QML
side we only expose newTab(url) and only from C++ side we're calling
newTab with parent id and browsing context.
This change requires https://github.com/sailfishos/qtmozembed/pull/30

[browser] Pass back browsing context when web content requested new window. Fixes JB#56631 OMP#JOLLA-569

---

apps/core/declarativewebcontainer.cpp
apps/core/declarativewebcontainer.h
apps/core/webpagequeue.cpp
apps/core/webpagequeue.h
apps/core/webpages.cpp
apps/core/webpages.h
apps/history/declarativetabmodel.cpp
common/opensearchconfigs.pri
defaults.pri
tests/auto/mocks/declarativewebcontainer/declarativewebcontainer.cpp
tests/auto/mocks/declarativewebcontainer/declarativewebcontainer.h
tests/auto/test_common.pri

This makes sure that an OOM killed parent tab is activated
when a child tab is closed.
Might be easier to review per commit.

Check unique id from WebPageEntry instead of live page

---

apps/core/declarativewebcontainer.cpp
apps/core/declarativewebcontainer.h
apps/core/webpagequeue.cpp
apps/core/webpagequeue.h
apps/core/webpages.cpp
apps/core/webpages.h
apps/history/declarativetabmodel.cpp
tests/auto/mocks/declarativewebcontainer/declarativewebcontainer.cpp
tests/auto/mocks/declarativewebcontainer/declarativewebcontainer.h

When closing the active tab that was not created
by JavaScript, activate the tab that was used before the tab
that got closed.
If tab was created by JavaScript, the parent tab of the child
is activated.
From user point of view this should result more understandable activation
as user likely remembers the tab that she was using before current
active tab.

[browser] Activate recently used tab when closing the active tab. Fixes JB#56968

---

apps/browser/qml/pages/components/Overlay.qml
apps/browser/qml/pages/components/PopUpMenuFooter.qml
apps/browser/qml/pages/components/PopUpMenuItem.qml
apps/browser/qml/pages/components/ToolBar.qml

Closing annoying popups has become really hard with 4.2.0.19, because the close button wasn't clickable anymore. This happened for 3 reasons, the Animator sets the Overlay to disabled, the Flickable of the PopUpMenu covers the button and the InvertedMouseArea also stole the input from it. 0c03d773f2dd06a79612c45f0e9533950a39e41a fixes the Flickable covering the button, so we only needed to remove the `enabled: false` property change on the animator and make the InvertedMouseArea not steal inputs from it. That way the PopUpMenu still closes, when the close-tab button is pressed, but it also closes the tab, which imo is the right behaviour. The back button is now also clickable and closes the menu as well (and navigates back).
<del>
Because I thought the close button not working was an …

RFC: Bring back the close button in the toolbar

---

tests/manual/leak-test/cycle.js
tests/manual/leak-test/styles.css
tests/manual/manual.pro
tests/manual/test-leaky-image.html
tests/manual/test-leaky-video.html
tests/manual/testpage.html

Adds two pages for testing memory leaks when cloning videos and images respectively.
Image cloning doesn't exhibit any memory leaks on ESR78, whereas video cloning clearly does.

[browser] Add memory leak test pages. Contributes to JB#56707

---

data/ua-update.json
data/ua-update.json.in
data/ua/78.0/ua-update.json

I found that changing user-agent to desktop Firefox one helps to fix the problem of constantly reloading m.vk.com page (it starts reloading after you log in). Looks like it is a site problem and we need to adjust our user-agent to overcome it.
I will add the JB task number later when I get my Jolla account.

[user-agent] Update preprocessed user agent overrides for m.vk.com. Fixes JB#57309

---

apps/history/declarativetabmodel.cpp
apps/history/declarativetabmodel.h
tests/auto/tst_webview/tst_webview.cpp

Makes the tst_webview test cases to pass. However, the test case itself segfault at the end as we're missing proper engine shutdown. Will create another PR to tackle engine shutdown -- needs to bit more thinking.

Test case fixing

---

tests/auto/common/testobject.cpp
tests/auto/common/testobject.h
tests/auto/tst_webview/tst_webview.cpp

This PR contains several commits. Might be easier to review per commit.
Seems to exit now quite reliable but I think that exit occasionally segfaults still. I'll keep eye on the test case.

Stop embedding after views&window destoyed (tst_webview)

---

apps/browser/qml/pages/BrowserPage.qml

For example now can be increased to 5 simple by:
> dconf write /apps/sailfish-browser/settings/max_live_tab_count 5

[browser] Make it possible to configure max live tab count via setting. Fixes JB#57511

---

tests/auto/tst_declarativehistorymodel/tst_declarativehistorymodel.cpp

The history model orders entries first by date descending, followed by url alphabetical ascending. Consequently if the time ticks over a second while the entries are added, the ordering can change.
Removing the entries by url rather than by index ensures the tests don't fail in case this happens.
As an alternative we could change the urls to force the correct order, but then the tests would rely on potentially brittle DBWorker behaviour (the returned ordering), so avoiding direct use of the index seemed preferable.
The tests successfully ran 100 cycles without failure after the change.

[tests] Stabilize declarativehistorymodel test case. Fixes JB#57681

---

tests/auto/tst_webview/tst_webview.cpp

This fixes the most frequent crashes for me, didn't manage to fully debug root cause but looks like the context during cleanup was the issue. Dropped WebEngineSettings as well because it caused similar problems.

[browser] Webview test crash fix. Fixes JB#57619
