src/declarativewebcontainer.cpp, src/pages/components/Overlay.qml
Contains two commits:
[sailfish-browser] Mark first time usage as done when a tab is activated
[sailfish-browser] Load incoming url also when first use is not done
=> First usage improvaments

src/dbworker.cpp, src/dbworker.h
=> [dbworker] Refactor DB migration code to use schema versions

tests/auto/tst_webview/tst_webview.cpp
Added conditional checking of the title change when loading
a url in tst_webview.
=> [unittests] Check conditionally title change in tst_webview

content/bookmarks.json, src/bookmarkmanager.cpp, src/bookmarkmanager.h, src/declarativebookmarkmodel.cpp, src/declarativebookmarkmodel.h, tests/auto/tst_declarativebookmarkmodel/tst_declarativebookmarkmodel.cpp
Also this PR makes the bookmarks ordered.
=> Bookmarks update

src/pages/components/TabView.qml
Contains two commits.
- Change private mode after pulley is closed
- Add opacity fade for private mode texture
=> Private mode pulley fix

src/declarativewebcontainer.cpp, src/declarativewebcontainer.h
…nested children. Contributes to JB#30188
=> [sailfish-browser] Communicate to the compositor that the window has nested children. Contributes to JB#30188

content/bookmarks.json, src/bookmarkmanager.cpp
=> [sailfish-browser] Update default bookmarks. Fixes JB#29786

src/pages/components/OrientationFader.qml
Remove unnecessary parallel animation and change fade in
animation to be a sequental animation so that total duration increases
by the pause animations.
=> [sailfish-browser] Polish orientation fading animation. Contributes to JB#30405

src/declarativetabmodel.cpp, src/declarativetabmodel.h, src/pages/components/Overlay.qml, src/pages/components/TabItem.qml
This commit adds activeTab role to the tab model.
=> [sailfish-browser] Update tab highlight when a tab is changed. Fixes JB#26301

src/dbmanager.cpp, src/dbmanager.h, src/declarativetabmodel.cpp, src/declarativetabmodel.h, src/persistenttabmodel.cpp, src/privatetabmodel.cpp, tests/auto/auto.pro, tests/auto/common/declarativewebpage.cpp, tests/auto/common/declarativewebpage.h, tests/auto/tests.xml, tests/auto/tst_persistenttabmodel/tst_persistenttabmodel.cpp, tests/auto/tst_persistenttabmodel/tst_persistenttabmodel.pro
Depends on https://github.com/tmeshkova/qtmozembed/pull/142
=> Reimplement unit tests for PersistentTabModel with isolated cases.

rpm/sailfish-browser.spec, src/browser.qml
…o open tabs. Fixes JB#30818
Inform ApplicationWindow rather than the cover window that the web
view is the main application window.
=> [sailfish-browser] Fix the browser cover not showing when there are no open tabs. Fixes JB#30818

src/declarativewebutils.cpp
Includes two commits. First one sorts Qt related includes in webutils (should be done everywhere).
=> Remove fixed press and hold delay

src/declarativewebutils.cpp
This PR depends on
https://github.com/tmeshkova/gecko-dev/pull/84
https://github.com/nemomobile-packages/gecko-dev/pull/51
and https://github.com/tmeshkova/qtmozembed/pull/144 merged to the nemomobile repo.
=> [prefs] Adjust touch tolerance to actual device DPI

src/declarativewebutils.cpp, src/declarativewebutils.h, src/pages/BrowserPage.qml, src/sailfishbrowser.cpp
Don't try to load -debugMode as url. This also cleans up webutils a bit.
Signed-off-by: Raine Makelainen <raine.makelainen@jolla.com>
=> Cleanup debugMode

src/qtmozembed/declarativewebpage.cpp
Reset margins when a page is loaded and when fullscreen height
changes.
=> Improve resetting margins

src/pages/components/ConfigWarning.qml
=> [qml] Remove PageStackAction.Replace for about:config dialog. Fixes JB#32873

src/pages/BrowserPage.qml
=> [sailfish-browser] Open external urls in new tab. Fixes JB#19746

common/browserpaths.cpp, common/browserpaths.h, src/declarativewebutils.cpp, src/downloadmanager.cpp, src/downloadmanager.h, src/downloadmimetypehandler.cpp, src/downloadmimetypehandler.h, src/src.pro, tests/auto/auto.pro, tests/auto/tst_downloadmimetypehandler/tst_downloadmimetypehandler.cpp, tests/auto/tst_downloadmimetypehandler/tst_downloadmimetypehandler.pro
=> [sailfish-browser] Add myapp to known mime content types. Contributes JB#34236

src/pages/components/WebView.qml
@pvuorela @siteshwar review :+1:
=> [sailfish-browser] Code style polish

oneshot.d/browser-update-default-data
=> [sailfish-browser] Fix/improve update-default-data oneshot script.. Contributes to JB#35001

data/ua-update.json, data/ua-update.json.in
=> [user-agent] Update user agent overrides for Gecko 38. Fixes JB#35224

src/core/declarativewebcontainer.cpp
As external urls are loaded always to new tab, we need to
wait that browser is initialized (context, mozwindow, and model are ready).
After browser initialized, we can proceed initialization steps normally.
This also fixes overwriting the existing active tab with the external
url when browser is started.
=> [sailfish-browser] Activate tabs only after browser initialized. Fixes JB#35387

rpm/sailfish-browser.spec, src/browser/browser.cpp, src/browser/closeeventfilter.cpp, src/browser/declarativewebutils.cpp, src/browser/declarativewebutils.h, src/browser/downloadmanager.cpp, src/browser/downloadmanager.h, src/core/declarativewebcontainer.cpp, src/core/settingmanager.cpp, src/core/webpages.cpp, src/pages/BrowserPage.qml, src/pages/components/ConfigDialog.qml, src/pages/components/DownloadMenuItem.qml, src/qtmozembed/declarativewebpage.cpp, src/qtmozembed/declarativewebpagecreator.cpp, src/src.pro, tests/auto/mocks/declarativewebutils/declarativewebutils.cpp, tests/auto/mocks/declarativewebutils/declarativewebutils.h, tests/auto/mocks/qmozcontext/qmozcontext.cpp, tests/auto/mocks/qmozcontext/qmozcontext.h, tests/auto/tst_declarativewebcontainer/tst_declarativewebcontainer.cpp, tests/auto/tst_webpages/tst_webpages.cpp, tests/auto/tst_webutils/tst_webutils.pro, tests/auto/tst_webview/tst_webview.cpp, tests/auto/tst_webview/tst_webview.pro
Requires: https://git.merproject.org/mer-core/qtmozembed/merge_requests/18
=> Use improved context api

src/pages/components/AuthDialog.qml
…bility. Contributes to JB#33148
=> [sailfish-browser] Allow toggling authentication dialog password visibility. Contributes to JB#33148

data/ua-update.json.in
Got broken by:
https://github.com/sailfishos/sailfish-components-webview/blob/master/lib/webengine.h#L23
@chriadam review ?
=> [sailfish-browser] Fix user-agent override pattern matching. Contributes to JB#30687

tests/manual/testgeolocation.html
Adds current position to the map (single shot) and position watcher.
=> [sailfish-browser] Improve geo location manual test. Contributes to JB#40423

src/pages/components/TabView.qml
=> Add remorse popup for closing all tabs

src/browser.qml, src/pages/BrowserPage.qml, src/pages/components/ConfigDialog.qml, src/pages/components/FavoriteGrid.qml, src/pages/components/Overlay.qml, src/pages/components/WebView.qml
In theory we could also use pageStack.currentPage.asyncObject.pageCompleted
internals but this takes care of synchronous page pushes as well.
Having pagePush method on the browser side is not enough as there
can be arbitrary page push / pushAnimator calls from the components
that browser is using.
=> Create background for each page if doesn't background exists

src/pages/components/Overlay.qml, src/pages/components/OverlayAnimator.qml
Respect keyboard focus for the overlay.
=> Cleanup old overlay active handling

rpm/sailfish-browser.spec
=> [browser] Require sailfish-content-graphics instead of jolla-ambient. Contributes to JB#32401

data/ua-update.json.in
There's still something wrong with the regexp overrided hosts.
=> [ua-overrides] Update user-agent overrides. Contributes to JB#42873

src/qtmozembed/declarativewebpage.cpp
Also triggering capture is guarded only for active web pages.
=> [browser] Guard capture grab ready for active web page. Contributes to JB#44721

data/ua-update.json.in
=> [ua] Introduce google overrides for few other country level domains. Fixes JB#45761

rpm/sailfish-browser.spec
=> [sailfish-browser] Fix rpm license. Contributes to JB#45486

rpm/sailfish-browser.spec, settings/Privacy.qml, src/pages/components/DownloadRemorsePopup.qml, src/pages/components/Overlay.qml, src/pages/components/TabButton.qml, src/pages/components/TabView.qml
=> [browser] Adapt remorse popup usage to the new design. Contributes JB#46248

backup-unit/Browser.json, backup-unit/backup-unit.pro, backup-unit/browserunit.cpp, rpm/sailfish-browser.spec, sailfish-browser.pro, src/core/logging.cpp, src/core/logging.h
Moved backup unit here from jolla-vault. Reduced the usage of qtaround
=> [sailfish-browser] Add backup unit. Contributes to JB#29667

rpm/sailfish-browser.privileges, src/pages/components/ResourceController.qml, src/pages/components/TextSelectionController.qml
@rainemak @monich review please? Are there any issues with changing privileges?
=> Jb48425 remove statefs

rpm/sailfish-browser.spec
Run oneshots for new users if needed and for all users in users group.
=> [sailfish-browser] Run oneshots for everyone. Contributes to JB49024

src/browser/declarativewebutils.cpp
=> [browser] Take user agent value for preference from dconf. Fixes JB#49917

tests/manual/testgeolocation.html
Redesign testgeoloction page to test watchPosition and clearWatch call combinations.
=> [sailfish-browser] Improve geo location manual test. Contributes to JB#50110

tests/manual/test-fullscreen-video-l.html, tests/manual/test-fullscreen-video-s.html, tests/manual/test-iframe.html, tests/manual/test-subframe.html, tests/manual/testanchors.html, tests/manual/testfilepicker.html, tests/manual/testgeolocation.html, tests/manual/testhtml5audio.html, tests/manual/testlocalization.html, tests/manual/testmouseclick.html, tests/manual/testpage.html, tests/manual/testtouchclick.html, tests/manual/testurlscheme.html, tests/manual/testuseragent.html
Small annoyance fixed so that I don't need always pinch in the test case.
=> [sailfish-browser] Use viewport meta for filepicker testcase. JB#51225

src/browser/downloadmanager.cpp, src/browser/downloadmanager.h, src/pages/components/SecondaryBar.qml
=> [sailfish-browser] Block the Print to PDF button while printing. Contributes to JB#51205

apps/shared/OrientationFader.qml
Cherry-pick from master d8daee197e3391fd3e1ee9fa2994f6bbde6b8b14
Original bug id 36210.
=> [sailfish-browser] Add fallback timer for orientation fader. Fixes JB#52103

backup-unit/browserunit.cpp
This only fixes backing up. Older backups can not be restored correctly
with this change.
=> [sailfish-browser] Fix backup. Contributes to JB#52318

apps/browser/qml/pages/BrowserPage.qml, apps/browser/qml/pages/components/Overlay.qml, apps/history/declarativetabmodel.cpp, apps/shared/OverlayAnimator.qml
https://bz.jollamobile.com/show_bug.cgi?id=53170
=> [sailfish-browser] Make overlay to open to top (y: 0) if no tabs exists. Fixes JB#53170

apps/browser/qml/pages/components/Overlay.qml
https://bz.jollamobile.com/show_bug.cgi?id=53171
=> [sailfish-browser] Add history item below the search field. Fixes JB#53171

sailfish-browser.desktop
Requires: https://github.com/sailfishos/sailjail-permissions/pull/55
=> Rename Mozilla permission to WebView.

apps/browser/qml/pages/components/Overlay.qml
Animate overlay when last tab is closed from toolbar.
=> Animate overlay when closing last tab.

tests/manual/testpage.html, tests/manual/testpopupwindows.html
Renamed file since pop-ups can reference objects beyond pop-up windows. Added tags to file.
=> [sailfish-browser] Add pop-up test page. Contributes to JB#53682

apps/browser/qml/pages/PrivacySettingsPage.qml, apps/shared/PopupBlockedDialog.qml, apps/shared/WebView.qml
We want to notify the user when pop-ups are blocked.
Handling embed:popupblocked allows to get these events.
=> [sailfish-browser] Add PopupBlockerDialog. Contributes to JB#52731

tests/manual/testloginform.html, tests/manual/testpage.html
Adds a manual test page to simulate account registration and login
pages, useful for testing the username/password autocomplete feature.
=> Add login/register form manual test page

tests/manual/testwebprompts.html
=> [sailfish-browser] Manual test for multiple popups. JB#51913 OMP#JOLLA-94

apps/browser/main.cpp, apps/browser/settings/declarativeloginmodel.cpp, apps/browser/settings/declarativeloginmodel.h, apps/browser/settings/loginfiltermodel.cpp, apps/browser/settings/loginfiltermodel.h, apps/browser/settings/logininfo.cpp, apps/browser/settings/logininfo.h, apps/browser/settings/settings.pri
Adds models to allow management of logins (usernames and passwords)
through the frontend.
=> Add login management models

apps/browser/qml/pages/BrowserPage.qml, apps/captiveportal/qml/pages/CaptivePortalPage.qml, apps/core/declarativewebcontainer.cpp, apps/shared/WebView.qml, rpm/sailfish-browser.spec
Requires:
https://git.sailfishos.org/mer-core/qtmozembed/merge_requests/96
=> Use renamed backgroundColor property

apps/browser/qml/pages/components/BookmarkEditDialog.qml, rpm/sailfish-browser.spec
UserPrompt has been replaced with UserPromptDialog.
See: https://github.com/sailfishos/sailfish-components-webview/pull/104
=> Update UserPrompt for customizable popups

tests/manual/index.html, tests/manual/testmarginbottom.html, tests/manual/testpage.html
Also adds a redirect from index.html to the contents listing, because I can never remember the correct name of the page.
There's a test version of the test page here: https://www.flypig.co.uk/tests/bottom-margin.html
Thanks Pavel for the nice input on this.
=> Add a page for testing the bottom margin changes

apps/browser/qml/pages/BrowserPage.qml, apps/browser/qml/pages/components/Overlay.qml, apps/browser/qml/pages/components/OverlayListItem.qml, apps/browser/qml/pages/components/PopUpMenu.qml, apps/browser/qml/pages/components/PopUpMenuFooter.qml, apps/browser/qml/pages/components/PopUpMenuItem.qml, apps/browser/qml/pages/components/ToolBar.qml, apps/shared/OverlayAnimator.qml
The menu should be displayed by pressing a button, hidden by tap in a free area:
=> [sailfish-browser] New site pop-up menu. Contributes to JB#51692

apps/browser/qml/pages/SettingsPage.qml, apps/browser/qml/pages/components/BrowserListItem.qml
Ensures icons and glassitems are vertically aligned at their centres and that the text is vertically aligned on the left.
=> Align items on Settings page

apps/browser/qml/pages/BrowserPage.qml
Requires https://github.com/sailfishos/sailjail-permissions/pull/81
=> [browser] Open start page when tab count reaches zero. Fixes JB#54408 OMP#JOLLA-162

apps/browser/settings/declarativeloginmodel.cpp, tests/auto/auto.pro, tests/auto/tests.xml, tests/auto/tst_logins/ResourceControllerMock.qml, tests/auto/tst_logins/tst_logins.cpp, tests/auto/tst_logins/tst_logins.pro, tests/auto/tst_logins/tst_logins.qml, tests/auto/tst_logins/tst_logins.qrc, tests/auto/tst_webview/tst_webview.cpp, tests/auto/tst_webview/tst_webview.pro, tests/auto/tst_webview/tst_webview.qml
Builds on #838.
Current WIP implementation gets the existing webview tests to pass, I'll add the login unit tests on top in the same PR.
=> Add unit tests for the browser login and passwords page

apps/browser/qml/pages/PrivacySettingsPage.qml, apps/browser/qml/pages/SettingsPage.qml
Move "Do Not Track" TextSwitch to Settings Page. Add section headers and redesign "privacy" button
=> [sailfish-browser] Redesign SettingsPage and PrivacySettingsPage. Contributes to JB#54798

apps/browser/qml/pages/SettingsPage.qml
Fix initially highlighted item in ComboBox for choosing home page
=> [browser] Fix initial currentIndex in ComboBox for choosing home page. Fixes JB#54820

apps/browser/qml/pages/PermissionExceptionsPage.qml
No bug id for this one. Will come along with next tag.
=> Center ValueButton vertically on permission exceptions page

apps/core/declarativewebutils.cpp, data/ua-update.json.in
This also updates ua override default download uri.
=> Adapt user-agent overrides json for the newer engine

apps/browser/qml/pages/PrivacySettingsPage.qml, apps/core/settingmanager.cpp, apps/core/settingmanager.h, apps/storage/dbmanager.cpp, apps/storage/dbmanager.h, apps/storage/dbworker.cpp, apps/storage/dbworker.h
Add browsing history erasing within periods (last day, last week, last 4 weeks, everything).
"Last 4 weeks" is used here because the initial suggestion to use "Last month" is vague: we can set the period to {31, 30, 29, 28} days.
=> [browser] Add history erasing within periods. JB#55578

apps/browser/qml/pages/PrivacySettingsPage.qml, apps/browser/qml/pages/SettingsPage.qml, apps/browser/qml/pages/components/BrowserDataItem.qml, apps/browser/qml/pages/components/PrivacySettingsConfirmDialog.qml
It depends on
https://github.com/sailfishos/embedlite-components/pull/66
https://github.com/sailfishos/embedlite-components/pull/70
https://github.com/sailfishos/sailfish-browser/pull/933
https://github.com/sailfishos/sailfish-browser/pull/938
=> [sailfish-browser] Add confirm dialog of clearing browser data. JB#56153

.gitignore
This doesn't contain changelog entry as this doesn't affect the build.
=> Add sailfish-browser-pro.user to .gitignore

apps/browser/qml/pages/BrowserPage.qml, apps/browser/qml/pages/components/DimmerEffect.qml, apps/browser/qml/pages/components/Overlay.qml, apps/browser/qml/pages/components/ToolBar.qml, apps/captiveportal/qml/pages/CaptivePortalPage.qml, apps/core/declarativewebcontainer.cpp, apps/history/declarativetabmodel.cpp, apps/history/declarativetabmodel.h, apps/history/persistenttabmodel.cpp, apps/history/persistenttabmodel.h, apps/history/privatetabmodel.cpp, apps/history/privatetabmodel.h, apps/qtmozembed/declarativewebpage.cpp, apps/qtmozembed/declarativewebpage.h, apps/shared/Background.qml, apps/shared/BrowserWindow.qml, apps/storage/dbmanager.cpp, apps/storage/dbmanager.h, apps/storage/dbworker.cpp, apps/storage/dbworker.h, apps/storage/tab.cpp, apps/storage/tab.h, tests/auto/mocks/declarativewebpage/declarativewebpage.h, tests/auto/tst_dbmanager/tst_dbmanager.cpp, tests/auto/tst_persistenttabmodel/tst_persistenttabmodel.cpp, tests/auto/tst_webview/tst_webview.cpp
See also: https://github.com/sailfishos/qtmozembed/pull/28
=> Create tab early and update resolved url only after it is resolved

tests/manual/testpage.html
The bug is not triggering always but at least with this it's relatively easy to get it reproduced and backtrace from it.
=> [browser] Add test case for target="_blank" download triggering. JB#56631 OMP#JOLLA-569

tests/manual/testurlscheme.html
This should be simple enough test case for this.
=> [browser] Add test case for opening tel uri into a new tab. JB#56648 OMP#JOLLA-577
